export enum AuthTokenType {
  EMAIL_VERIFICATION_TOKEN = 'EMAIL_VERIFICATION_TOKEN',
  PHONE_VERIFICATION_TOKEN = 'PHONE_VERIFICATION_TOKEN',
  RESET_PASSWORD_VERIFICATION_TOKEN = 'RESET_PASSWORD_VERIFICATION_TOKEN',
}
