services:
  frontend:
    build:
      context: ./edufluxweb
      dockerfile: DockerFile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3000

  backend:
    build:
      context: ./EduFlux_Backend
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    env_file:
      - ./EduFlux_Backend/.env
    environment:
      - NODE_ENV=development
